spring:
  application:
    name: dy-sch-au

  data:
    mongodb:
      host: localhost
      port: 27017
      database: dyscau
      uri: mongodb://localhost:27017/dyscau
      auto-index-creation: true

  jackson:
    time-zone: America/Bogota

  datasource:
    hikari:
      timezone: America/Bogota

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Bogota
